### PR TITLE
coffee 1.9.1 utilities rename:

### PR DESCRIPTION
**Pull request by michal-novacek**
__hasProp to hasProp
__extends to extend
__slice to slice
__bind to bind
__indexOf to indexOf

### CODE REVIEW

**Comment by steida** [comment]
Why closed? It looks promising.

**Comment by michal-novacek** [comment]
Running "esteBuilder:testApp" (esteBuilder) task
Compiling..
>> /var/folders/xh/9h2j5h_53kq9hjctgvm3cq7c0000gp/T/1424478246004.381/test_app/js/employee.js:13: ERROR - variable superClass is undeclared
>> goog.inherits(app.Employee, superClass);
>>                             ^
>> 
>> 1 error(s), 0 warning(s)
Warning: Task "esteBuilder:testApp" failed. Use --force to continue.

not sure how to fix that

**Comment by steida** [comment]
Stay with previous CoffeScript version. I will fix it later.

**Comment by michal-novacek** [comment]
I did a diff between Employee.coffee in 1.9.0 and 1.9.1 and it looks like they also renamed _super to superClass. When I change that it seems to work fine. I made a new PR at https://github.com/steida/coffee2closure/pull/8

**Comment by steida** [comment]
Thank you, will check it soon.

**Pull request closed without merging**
